# Generated by Django 4.2.5 on 2025-02-21 01:20

from django.db import migrations, models
import filemanager.models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(default=1, upload_to=filemanager.models.document_upload_path),
            preserve_default=False,
        ),
    ]
