# Generated by Django 4.2.5 on 2023-10-05 14:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filemanager', '0002_staffcomments_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='commented',
        ),
        migrations.AddField(
            model_name='document',
            name='comments_by',
            field=models.ManyToManyField(related_name='comments_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
