# Generated by Django 4.2.5 on 2023-10-11 10:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filemanager', '0005_document_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='share_with',
            field=models.ManyToManyField(related_name='shared_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
