# Generated by Django 4.2.5 on 2023-10-11 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0006_alter_document_share_with'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='folder',
        ),
    ]
