# Generated by Django 4.2.5 on 2023-10-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0007_remove_document_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='staff_comments',
            field=models.ManyToManyField(to='filemanager.staffcomments'),
        ),
    ]
